[package]
name = "daemon_with_loader"
version = "0.0.1"
authors = ["Karl Bergström <karl.anton.bergstrom@gmail.com>"]
edition = "2018"
readme = "README.md"
license = "MIT/Apache-2.0"
publish = false

[dependencies]
distill = { version = "=0.0.3", path = "../../", features = ["type_uuid", "distill-daemon", "distill-importer"] }
image2 = { version = "0.11", features = ["ser"] }
tracing = "0.1"
serde = "1"
uuid = "0.8.2"
bincode = "1.3.1"
futures-util = { version = "0.3", default-features = false }
futures-io = { version = "0.3", default-features = false }
futures-core = { version = "0.3", default-features = false, features = ["alloc"] }
tracing-subscriber = "0.2.23"
